package com.example.protal.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.bean.AjiaItemDesc;
import com.example.bean.AjiaItemDescExample;
@Mapper
public interface AjiaItemDescMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    long countByExample(AjiaItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    int deleteByExample(AjiaItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    int deleteByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    int insert(AjiaItemDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    int insertSelective(AjiaItemDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    List<AjiaItemDesc> selectByExampleWithBLOBs(AjiaItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    List<AjiaItemDesc> selectByExample(AjiaItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    AjiaItemDesc selectByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") AjiaItemDesc record, @Param("example") AjiaItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") AjiaItemDesc record, @Param("example") AjiaItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    int updateByExample(@Param("record") AjiaItemDesc record, @Param("example") AjiaItemDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    int updateByPrimaryKeySelective(AjiaItemDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(AjiaItemDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_desc
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    int updateByPrimaryKey(AjiaItemDesc record);
}