package com.example.protal.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.bean.AjiaItemParam;
import com.example.bean.AjiaItemParamExample;
@Mapper
public interface AjiaItemParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    long countByExample(AjiaItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    int deleteByExample(AjiaItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    int insert(AjiaItemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    int insertSelective(AjiaItemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    List<AjiaItemParam> selectByExampleWithBLOBs(AjiaItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    List<AjiaItemParam> selectByExample(AjiaItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    AjiaItemParam selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") AjiaItemParam record, @Param("example") AjiaItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") AjiaItemParam record, @Param("example") AjiaItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    int updateByExample(@Param("record") AjiaItemParam record, @Param("example") AjiaItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    int updateByPrimaryKeySelective(AjiaItemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(AjiaItemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ajia_item_param
     *
     * @mbg.generated Wed Jan 31 17:22:15 CST 2018
     */
    int updateByPrimaryKey(AjiaItemParam record);
}